import { defineConfig } from 'orval';

// `pnpm api:generate` writes openapi.json from the API, then runs this. Everything under
// src/generated is replaced on every run (`clean` only touches that folder), so never edit it.
export default defineConfig({
  voltdrop: {
    input: { target: './openapi.json' },
    output: {
      target: './src/generated/voltdrop.ts',
      mode: 'single',
      client: 'react-query',
      httpClient: 'fetch',
      clean: true,
      override: {
        // Every request goes through apiFetch: base URL, headers, and ApiProblem on errors.
        mutator: { path: './src/fetcher.ts', name: 'apiFetch' },
        // Generated functions return the response body; errors are thrown, never returned.
        fetch: { includeHttpResponseReturnType: false },
        query: { version: 5, signal: true },
        // No timestamp or version, so regenerating an unchanged API changes nothing.
        header: () => [
          'Generated by orval from packages/api-client/openapi.json. Do not edit.',
          'Regenerate with `pnpm api:generate`.',
        ],
      },
    },
  },
});
